#ifndef __APP_SKILL_H__
#define __APP_SKILL_H__

typedef enum {
    MEDIA_IDLE,
    MEDIA_PLAYING,
    MEDIA_PAUSE,
    MEDIA_MAX,
} dui_media_state_t;

#if 0
/*qiudong：废弃代码，第三方公司业务*/
typedef enum {
    //COMMAND技能
    DUI_SKILL_CTRL_UNKNOWN = 0,
    DUI_PLAYER_CTRL_PAUSE,
    DUI_PLAYER_CTRL_RESUME,
    DUI_PLAYER_CTRL_PREV,
    DUI_PLAYER_CTRL_NEXT,
    DUI_PLAYER_CTRL_STOP,
    DUI_PLAYER_CTRL_FORWARD,
    DUI_PLAYER_CTRL_BACKWARD,
    DUI_PLAYER_CTRL_MUTE,
    DUI_PLAYER_CTRL_CANCELMUTE,
    DUI_PLAYER_CTRL_INCREASE_VOICE,  //10
    DUI_PLAYER_CTRL_DECREASE_VOICE,
    DUI_PLAYER_CTRL_MIN_VOICE,
    DUI_PLAYER_CTRL_MAX_VOICE,
    DUI_PLAYER_CTRL_SET_VOICE,
    DUI_PLAYER_CTRL_REPLAY, //15
    DUI_PLAYER_CTRL_SEQUENCY,
    DUI_PLAYER_CTRL_RANDOM,
    DUI_PLAYER_CTRL_LOOP,
    DUI_PLAYER_CTRL_FAVORITE,
    DUI_PLAYER_CTRL_CANCELFAVORITE,  //20
    DUI_PLAYER_CTRL_PLAYFAVORITE,   
    DUI_PLAYER_CTRL_PLAYMODE,
    //NATIVE技能
    DUI_PLAYER_CTRL_QUERY,
    DUI_PLAYER_CTRL_MUSIC,
    DUI_CLEAN_ROBOT_CLEAN,
    DUI_CLEAN_ROBOT_CHARGING,
    DUI_CLEAN_ROBOT_SKILLS,  //27
    DUI_CLEAN_ROBOT_LOCAL_CLEAN,
    DUI_CLEAN_ROBOT_MAPPING,
    DUI_CLEAN_ROBOT_STATION,
    DUI_CLEAN_ROBOT_CALL_CLEAN,
    DUI_CLEAN_ROBOT_STATION_TASK,   //32
    DUI_CLEAN_ROBOT_PATTERN_SWITCH,
    DUI_CLEAN_ROBOT_PATTERN_QUERY,
    DUI_CLEAN_ROBOT_LOCATION_QUERY,
    DUI_CLEAN_ROBOT_TASK_INTERVENE,
} dui_skill_ctrl_t;
#endif

typedef enum {
    DUI_SKILL_CTRL_UNKNOWN = 0,
	DUI_PLAYER_CTRL_RESUME,
	DUI_PLAYER_CTRL_PREV,
	DUI_PLAYER_CTRL_NEXT,
	DUI_PLAYER_CTRL_STOP,
	DUI_PLAYER_CTRL_FORWARD,
	DUI_PLAYER_CTRL_BACKWARD,
	DUI_PLAYER_CTRL_MUTE,
	DUI_PLAYER_CTRL_CANCELMUTE,
	DUI_PLAYER_CTRL_REPLAY,
	DUI_PLAYER_CTRL_SEQUENCY,
	DUI_PLAYER_CTRL_LOOP,
	DUI_PLAYER_CTRL_RANDOM,
	DUI_PLAYER_CTRL_FAVORITE,
	DUI_PLAYER_CTRL_PLAYFAVORITE,
	DUI_PLAYER_CTRL_CANCELFAVORITE,
	DUI_PLAYER_CTRL_SET_VOICE,
	DUI_PLAYER_CTRL_PLAYMODE,
	DUI_PLAYER_CTRL_PAUSE,
   	DUI_CLEAN_ROBOT_CLEAN,
    DUI_CLEAN_ROBOT_CHARGING,
    DUI_CLEAN_ROBOT_SKILLS,
   	DUI_CLEAN_ROBOT_LOCAL_CLEAN,
    DUI_CLEAN_ROBOT_MAPPING,
    DUI_CLEAN_ROBOT_STATION,
    DUI_CLEAN_ROBOT_CALL_CLEAN,
    DUI_CLEAN_ROBOT_STATION_TASK,
    DUI_CLEAN_ROBOT_PATTERN_SWITCH,
    DUI_CLEAN_ROBOT_PATTERN_QUERY,
    DUI_CLEAN_ROBOT_LOCATION_QUERY,
    DUI_CLEAN_ROBOT_TASK_INTERVENE,
    //COMMAND技能
	DUI_SH_DEVICE_TURN_ON,	/*设备打开*/
	DUI_SH_DEVICE_TURN_OFF,	/*设备关闭*/
	DUI_SH_OPEN_MODE, 		/*打开模式(场景)*/
	//中控技能
	DUI_SYSTEM_SET_BRIGHTNESS,
	DUI_SYSTEM_SET_VOLUME,
} dui_skill_ctrl_t;


typedef struct {
    const char* cmd_name;
    dui_skill_ctrl_t skill_ctrl;

} dui_skill_ctrl_map_t;


int app_skill_handler(cJSON *command_js,bool is_native);


#endif

